In [53]:
import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [81]:
df=pd.read_csv("onion.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 282 entries, 0 to 281
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  282 non-null    int64
 1   Date        282 non-null    object
 2   price       282 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 6.7+ KB

In [82]:
d=df.pop('Unnamed: 0')
df

                    Date  price
0    2000-01-01 00:00:00   89.8
1    2000-02-01 00:00:00   77.4
2    2000-03-01 00:00:00   83.0
3    2000-04-01 00:00:00   81.6
4    2000-05-01 00:00:00   88.9
..                   ...    ...
277  2023-02-01 00:00:00  159.5
278  2023-03-01 00:00:00  138.1
279  2023-04-01 00:00:00  128.2
280  2023-05-01 00:00:00  129.2
281  2023-06-01 00:00:00  144.4

[282 rows x 2 columns]

In [83]:
#d=df.drop(columns=["Potatoes","Rice","Wheat","Maize"])
df.index=df.pop('Date')
#d['price']=d.pop('Onions')
df

                     price
Date
2000-01-01 00:00:00   89.8
2000-02-01 00:00:00   77.4
2000-03-01 00:00:00   83.0
2000-04-01 00:00:00   81.6
2000-05-01 00:00:00   88.9
...                    ...
2023-02-01 00:00:00  159.5
2023-03-01 00:00:00  138.1
2023-04-01 00:00:00  128.2
2023-05-01 00:00:00  129.2
2023-06-01 00:00:00  144.4

[282 rows x 1 columns]

In [84]:
#d=df[:-6]
#d

In [85]:
df.to_csv("onion.csv")